import perfume from "../assets/perfume.png";
import halfcaste from "../assets/halfcaste.png";
import showergel from "../assets/showergel.png";
import scrub from "../assets/scrub.png";
import cream from "../assets/cream.png";
import cleanser from "../assets/cleanser.png";
import glow from "../assets/glow.png";
import caste2 from "../assets/caste2.png";

export const products = [
  {
    id: 1,
    name: "Half Cast Soap (Big)",
    price: "₦3,000",
    originalPrice: "₦3,500",
    image: caste2,
    description: "Premium skin brightening soap for radiant glow.",
    rating: 4.7,
    reviews: 96,
    bestseller: true,
    organic: true,
    benefits: ["Brightening", "Cleansing", "Glowing"],
  },
  {
    id: 2,
    name: "Half Cast Soap (Small)",
    price: "₦1,700",
    originalPrice: "₦2,000",
    image: halfcaste,
    description: "Smaller size of our bestselling Half Cast soap.",
    rating: 4.6,
    reviews: 78,
    bestseller: false,
    organic: true,
    benefits: ["Cleansing", "Glowing", "Affordable size"],
  },
  {
    id: 3,
    name: "Whitening Shower Gel 500ml",
    price: "₦3,500",
    originalPrice: "₦4,000",
    image: showergel,
    description: "Luxurious whitening shower gel for soft bright skin.",
    rating: 4.8,
    reviews: 132,
    bestseller: true,
    organic: true,
    benefits: ["Brightening", "Cleansing", "Refreshing"],
  },
  {
    id: 4,
    name: "Glow Oil 500ml",
    price: "₦2,000",
    originalPrice: "₦2,500",
    image: glow,
    description: "Natural glowing shower gel for daily freshness.",
    rating: 4.7,
    reviews: 118,
    bestseller: false,
    organic: true,
    benefits: ["Glowing", "Moisturizing", "Gentle Cleansing"],
  },
  {
    id: 5,
    name: "Face and Body Scrub 300ml",
    price: "₦2,500",
    originalPrice: "₦3,000",
    image: scrub,
    description: "Exfoliating scrub for smooth radiant skin.",
    rating: 4.8,
    reviews: 145,
    bestseller: true,
    organic: true,
    benefits: ["Exfoliating", "Smoothing", "Refreshing"],
  },
  {
    id: 6,
    name: "Brightening & Moisturizing Face Cleanser",
    price: "₦6,300",
    originalPrice: "₦7,000",
    image: cleanser,
    description: "Gentle cleanser with Papaya, Carrot, Ginseng & Vitamin C.",
    rating: 4.9,
    reviews: 187,
    bestseller: true,
    organic: true,
    benefits: ["Brightening", "Moisturizing", "Gentle Cleansing"],
  },
  {
    id: 8,
    name: "Luxury Body Butter",
    price: "₦15,000",
    originalPrice: "₦18,000",
    image: cream,
    description: "Shea Butter, Coconut & Turmeric Oil for radiant soft skin.",
    rating: 4.8,
    reviews: 256,
    bestseller: true,
    organic: true,
    benefits: ["Softening", "Brightening", "Anti-aging"],
  },

  {
    id: 11,
    name: "Eimaan Signature Perfume",
    price: "₦12,000",
    originalPrice: "₦14,000",
    image: perfume,
    description: "Long-lasting fragrance that leaves a lasting impression.",
    rating: 4.7,
    reviews: 143,
    bestseller: true,
    organic: false,
    benefits: ["Long-lasting scent", "Confidence boosting", "Refreshing"],
  },
];
